name: Build Readme

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - uses: YuZhangWang/social-readme@main
        with:
          blog_rss_link: https://yuzhang.wang/atom.xml
          blog_limit: 6
          douban_name: 179948994
          douban_limit: 6
          blog_time_format: "%a, %d %b %Y %H:%M:%S %z"
          commit_message: Update readme rss by social-readme
          time_zone: "Asia/Shanghai"

  # update-wakatime:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: zylele/waka-readme@master
  #       with:
  #         SHOW_TITLE: true
  #         WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
